## Non Graded Challenge

Marchelly Gideon Tambunan

Batch 003

In [30]:
import numpy as np                      #import library
import matplotlib.pyplot as plt

In [22]:
t = np.array([[23, 50, 7, 12],          #membuat tensor dengan Python
               [57, 67, 99, 43],
               [75, 21, 57, 12],
               [87, 26, 18, 84]])


In [23]:
tensor = np.array([t])
tensor

array([[[23, 50,  7, 12],
        [57, 67, 99, 43],
        [75, 21, 57, 12],
        [87, 26, 18, 84]]])

In [24]:
a = np.array([[23, 50, 19],             #melakukan perkalian matriks
             [7, 12, 109],
             [57, 67, 98]])
b = np.array([17, 22, 19])

a * b

array([[ 391, 1100,  361],
       [ 119,  264, 2071],
       [ 969, 1474, 1862]])

In [25]:
a_transpose = a.transpose()               #melakukan transpose pada matriks

a_transpose

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

In [29]:
det_a = np.linalg.det(a)                  #melakukan determinan pada matriks
det_a

131344.0000000002

In [28]:
inv_a = np.linalg.inv(a)                  #melakukan inverse pada matriks
inv_a

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])