# NON Graded Challenge 1
## i. Perkenalan
`Marchelly Gideon Tambunan`\
`Hactive8 Student`\
`Batch : 003`

In [1]:
import numpy as np                 #import library

In [17]:
A = np.array([1,3])                 #membuktikan apakah A eigenvector dari B?
B = np.array([[1,-1],[6, -4]])

In [19]:
a,b = np.linalg.eig(B)

In [20]:
a

array([-1., -2.])

In [21]:
b

array([[0.4472136 , 0.31622777],
       [0.89442719, 0.9486833 ]])

In [22]:
A/np.linalg.norm(A)             #hasil dibawah terbukti bahwa A eigenvector dari B

array([0.31622777, 0.9486833 ])